### ISSUE TITLE
v3.11.0.alpha does not work with nextjs

### ISSUE THREAD

**Issue by H34D** [masa-finance/masa-react#444]
<img width="1061" alt="image" src="https://github.com/masa-finance/masa-react/assets/13647606/96c0a1ec-ac12-4bdd-ac7c-314fa4aa3fc5">

**Comment by H34D** [comment]
```
yarn run v1.22.21
$ next dev
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Ready in 1582ms
 ○ Compiling / ...
 ✓ Compiled / in 16.3s (3255 modules)
Using kebab-case for css properties in objects is not supported. Did you mean WebkitBackgroundClip?
Using kebab-case for css properties in objects is not supported. Did you mean WebkitTextFillColor?
 ⨯ node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js (24:20) @ window
 ⨯ ReferenceError: window is not defined
    at createQueryClientAndPersister (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:37:21)
    at eval (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:60:36) {
  page: '/'
}
null
 ○ Compiling /_error ...
 ✓ Compiled /_error in 3.8s (3257 modules)
 ⨯ ReferenceError: window is not defined
    at createQueryClientAndPersister (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:37:21)
    at eval (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:60:36)
 ⨯ node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js (24:20) @ window
 ⨯ ReferenceError: window is not defined
    at createQueryClientAndPersister (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:37:21)
    at eval (webpack-internal:///./node_modules/@masa-finance/masa-react/dist/src/masa-client/query-client.js:60:36) {
  page: '/'
```

**Comment by smartdevcom** [comment]
How could I contribute to this project?
